title: "Rohan Garg: Home"
email: rhn.grg@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My notes on different technical and non-technical things.
baseurl: ""
url: ""
twitter_username: rhn_grg
github_username:  rohgarg

markdown: kramdown
theme: minima
paginate: 5
